{% set name = "extend_orfs" %}
{% set version = load_setup_py_data().version %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7.13
  run:
    - python >=3.7.13
    - sys
    - pyranges >= 0.0.117
    - csv >= 1.0
    - pyfaidx >= 0.7.1
    - pandas >= 1.3.5
    - copy
    - easyterm

about:
  home: "https://github.com/JoanPAAL/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Description of project"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - marco-mariotti


 python_requires = >= 3.7.13
 install_requires =
    sys
    pyranges >= 0.0.117
    csv >= 1.0
    pyfaidx >= 0.7.1
    pandas >= 1.3.5
    copy
    easyterm
